#! /bin/sh

### BEGIN INIT INFO
# Provides:		iotweb
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Daniel family IOT web server
# Description: 
#  This is a web service that provides access to the daniel
#  family IOT Web.  The service is very low performance,
#  as it is based on ruby/shotgun, so do not abuse.
### END INIT INFO

set -e

PIDFILE=/var/run/iotweb.pid
DAEMON=/usr/sbin/rubydaemon

# /etc/init.d/iotweb: start and stop the iotweb web service

test -x ${DAEMON} || exit 0

umask 022

. /lib/lsb/init-functions

# Are we running from init?
run_by_init() {
    ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
}

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
	if init_is_upstart; then
	    exit 1
	fi
	log_daemon_msg "Starting web service:" "iotweb"
	if start-stop-daemon --start --quiet --oknodo --pidfile ${PIDFILE} --exec ${DAEMON} -- -c /etc/rubydaemon/iotweb.conf ; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
	;;
  stop)
	if init_is_upstart; then
	    exit 0
	fi
	log_daemon_msg "Stopping web service:" "iotweb"
	if start-stop-daemon --stop --quiet --oknodo --pidfile ${PIDFILE}; then
	    log_end_msg 0
	    rm -f ${PIDFILE}
	else
	    log_end_msg 1
	fi
	;;


  reload|force-reload)
	if init_is_upstart; then
	    exit 1
	fi
	log_daemon_msg "Reloading web service configuration:" "iotweb"
        if start-stop-daemon --stop --signal HUP --quiet --oknodo --pidfile $PIDFILE; then
            log_end_msg 0
        else
            log_end_msg 1
        fi	
	;;

  restart)
	if init_is_upstart; then
	    exit 1
	fi
	log_daemon_msg "Restarting web service:" "iotweb"
	if start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile ${PIDFILE}; then
	    rm -f ${PIDFILE}
	fi
	if start-stop-daemon --start --quiet --oknodo --pidfile ${PIDFILE} --exec ${DAEMON} -- -c /etc/rubydaemon/iotweb.conf ; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
	;;

  try-restart)
	if init_is_upstart; then
	    exit 1
	fi
	log_daemon_msg "Restarting iot web service" "iotweb"
	set +e
	start-stop-daemon --stop --quiet --retry 30 --pidfile ${PIDFILE}
	RET="$?"
	set -e
	case $RET in
	    0)
		# old daemon stopped
		rm -f ${PIDFILE}
		if start-stop-daemon --start --quiet --oknodo --pidfile ${PIDFILE} --exec ${DAEMON} -- -c /etc/rubydaemon/iotweb.conf ; then
		    log_end_msg 0
		else
		    log_end_msg 1
		fi
		;;
	    1)
		# daemon not running
		log_progress_msg "(not running)"
		log_end_msg 0
		;;
	    *)
		# failed to stop
		log_progress_msg "(failed to stop)"
		log_end_msg 1
		;;
	esac
	;;

  status)
	if init_is_upstart; then
	    exit 1
	fi
	status_of_proc -p ${PIDFILE} ${DAEMON} rubydaemon && exit 0 || exit $?
	;;

  *)
	log_action_msg "Usage: /etc/init.d/iotweb {start|stop|reload|force-reload|restart|try-restart|status}"
	exit 1
esac

exit 0
